config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :bookmarks
      resources :facilities
      resources :facility_genres
      resources :genres
      resources :prefectures
      resources :reviews
      resources :users

      root to: "facilities#index"
    end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  mount LetterOpenerWeb::Engine, at: "letter_opener" if Rails.env.development?
  # Defines the root path route ("/")
  root "static_pages#top"

  get 'guest_login', to: 'user_sessions#guest_login'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  get 'sign_up', to: 'users#new'
  get 'confirm_withdraw', to: 'users#confirm_withdraw'

  get 'privacy_policy', to: 'static_pages#privacy_policy'
  get 'terms_of_use', to: 'static_pages#terms_of_use'

  resources :bookmarks, only: %i[create destroy]
  resources :facilities, only: %i[index show]  do
    resources :reviews, shallow: true do
      resources :likes, only: %i[create destroy]
    end

    collection do
      get :bookmarks
    end
  end
  resources :users, only: %i[create destroy]
  resource :profile, only: %i[show edit update]
  resources :password_resets, only: %i[new create edit update]

end

app/views/shared/_back_to_previous_page.html.erb
<button class="flex mx-auto justify-center my-10 text-sm bg-transparent hover:bg-gray-500 text-gray-600 font-semibold hover:text-white py-2 px-4 border border-gray-500 hover:border-transparent rounded-full">
  <%= link_to t('defaults.back'), 'javascript:history.go(-1)' %>
</button>

app/views/shared/_before_login_header.html.erb
<header>
  <div class="navbar bg-base-100">
    <div class="flex-1">
      <a class="btn btn-ghost hover:bg-transparent normal-case text-xl text-gray-950" href="/">Find Suomi</a>
    </div>
    <div class="flex-none gap-2">
      <div class="navbar-end">
        <%= link_to t('defaults.login'), login_path, class: 'btn btn-outline w-max h-min' %>
      </div>
    </div>
  </div>
</header>

app/views/shared/_dropdown_search_form.html.erb
<div class="w-full max-w-xs space-y-4 my-8">
  <%= form_with model: @search_facility_form, scope: :q, url: facilities_path, method: :get do |f| %>
    <%= f.select :genre_id, Genre.pluck(:name, :id), { include_blank: 'ジャンル' }, class: 'select select-bordered text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50 w-full max-w-xs mt-3' %>
    <%= f.select :prefecture_id, Prefecture.selected_prefectures.pluck(:name, :id), { include_blank: '都道府県' }, class: 'select select-bordered text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50 w-full max-w-xs mt-3' %>
    <div class="text-center mt-4">
      <%= f.submit '検索', name: nil, class: 'btn btn-neutral btn-sm text-white' %>
    </div>
  <% end %>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_message" class="flex alert mb-10">
    <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
    <ul class="list-disc text-sm text-left pl-2">
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <% if message_type == 'success' %>
    <div role="alert" class="flex alert alert-success rounded-none">
      <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
      <span><%= message %></span>
    </div>
  <% elsif message_type == 'error' %>
    <div role="alert" class="flex alert alert-error rounded-none">
      <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
      <span><%= message %></span>
    </div>
  <% else %>
    <div role="alert" class="flex alert alert-warning rounded-none">
      <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" /></svg>
      <span><%= message %></span>
    </div>
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer footer-center p-3 bg-base-200 text-base-content rounded">
  <div class="grid grid-flow-col gap-4">
    <%= link_to 'お問い合わせ', 'https://forms.gle/sTjdf9j5H8JRrqUB7', class: 'link link-hover', target: :_blank, rel: 'noopener noreferrer' %>
    <%= link_to '利用規約', terms_of_use_path, class: 'link link-hover' %>
    <%= link_to 'プライバシーポリシー', privacy_policy_path, class: 'link link-hover' %>
  </div>
  <aside>
    <p>Copyright © 2023 - Find Suomi </p>
  </aside>
</footer>

app/views/shared/_header.html.erb
<header>
  <div class="navbar bg-base-100">
    <div class="flex-1">
      <a class="btn btn-ghost hover:bg-transparent normal-case text-xl text-gray-950" href="/">Find Suomi</a>
    </div>
    <div class="flex-none gap-2">
      <div class="dropdown dropdown-end">
        <label tabindex="0" class="btn btn-ghost">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="inline-block w-5 h-5 stroke-current"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path></svg>
        </label>
        <ul tabindex="0" class="mt-1 z-[1] p-2 shadow menu menu-sm dropdown-content bg-base-200 rounded-box w-44">
          <li class="text-base my-1">
            <%= link_to t('defaults.to_top'), root_path, class: 'nav-link' %>
          </li>
          <li class="text-base my-1">
            <%= link_to t('profiles.show.title'), profile_path, class: 'nav-link' %>
          </li>
          <li class="text-base my-1">
            <%= link_to t('facilities.bookmarks.title'), bookmarks_facilities_path, class: 'nav-link' %>
          </li>
          <li class="text-base my-1">
            <%= link_to t('defaults.logout'), logout_path, data: {turbo_method: :delete} %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</header>

app/views/shared/_keyword_search_form.html.erb
<div class="form-control w-full max-w-xs space-y-4 my-8">
  <%= form_with model: @search_facility_form, scope: :q, url: facilities_path, method: :get do |f| %>
    <div>
      <p class="text-base font-semibold mb-1">キーワード検索</p>
      <%= f.search_field :name, placeholder: '例: 渋谷 シナモンロール', class: 'block w-full rounded-md border-gray-300 shadow-sm focus:border-gray-400 focus:ring focus:ring-gray-200 focus:ring-opacity-50' %>
    </div>
    <div class="text-center mt-4">
      <%= f.submit '検索', name: nil, class: 'btn btn-neutral btn-sm text-white', id: 'keyword_search' %>
    </div>
  <% end %>
</div>