config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :bookmarks
      resources :facilities
      resources :facility_genres
      resources :genres
      resources :prefectures
      resources :reviews
      resources :users

      root to: "facilities#index"
    end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  mount LetterOpenerWeb::Engine, at: "letter_opener" if Rails.env.development?
  # Defines the root path route ("/")
  root "static_pages#top"

  get 'guest_login', to: 'user_sessions#guest_login'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  get 'sign_up', to: 'users#new'
  get 'confirm_withdraw', to: 'users#confirm_withdraw'

  get 'privacy_policy', to: 'static_pages#privacy_policy'
  get 'terms_of_use', to: 'static_pages#terms_of_use'

  resources :bookmarks, only: %i[create destroy]
  resources :facilities, only: %i[index show]  do
    resources :reviews, shallow: true do
      resources :likes, only: %i[create destroy]
    end

    collection do
      get :bookmarks
    end
  end
  resources :users, only: %i[create destroy]
  resource :profile, only: %i[show edit update]
  resources :password_resets, only: %i[new create edit update]

end

app/models/facility.rb
class Facility < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  belongs_to :prefecture

  has_many :bookmarks, dependent: :destroy
  has_many :users, through: :bookmarks
  has_many :facility_genres, dependent: :destroy
  has_many :genres, through: :facility_genres
  has_many :reviews, dependent: :destroy

  validates :name, presence: true
  validates :address, presence: true

  scope :by_genre, ->(genre_id) { joins(:facility_genres).where(facility_genres: { genre_id: }) }
  scope :by_prefecture, ->(prefecture_id) { where(prefecture_id:) }
  scope :keywords_contain, ->(word) { where('name LIKE ? OR description LIKE ? OR address LIKE ?', "%#{word}%", "%#{word}%", "%#{word}%") }
end

app/controllers/admin/facilities_controller.rb
module Admin
  class FacilitiesController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes(action_name)).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-demo.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/facilities_controller.rb
class FacilitiesController < ApplicationController
  skip_before_action :require_login

  def index
    @search_facilities_form = SearchFacilitiesForm.new(search_params)
    @facilities = @search_facilities_form.search.order(name: :asc)
  end

  def bookmarks
    @bookmark_facilities = current_user.bookmark_facilities.includes(:users).order(name: :asc)
  end

  def show
    @facility = Facility.find(params[:id])
    @review = Review.new
    @reviews = @facility.reviews.includes(:user).order(created_at: :desc)
  end

  private

  def search_params
    params[:q]&.permit(:name, :description, :address, :genre_id, :prefecture_id)
  end
end

app/views/facilities/_before_login_bookmark.html.erb
<%= link_to login_path do %>
  <svg
  xmlns="http://www.w3.org/2000/svg"
  fill="none"
  viewBox="0 0 24 24"
  stroke-width="1"
  stroke="currentColor"
  class="w-8 h-8"
  >
    <path
      stroke-linecap="round"
      stroke-linejoin="round"
      d="M17.593 3.322c1.1.128 1.907 1.077 1.907 2.185V21L12 17.25 4.5 21V5.507c0-1.108.806-2.057 1.907-2.185a48.507 48.507 0 0111.186 0z"　/>
  </svg>
<% end %>

app/views/facilities/_bookmark.html.erb
<%= turbo_frame_tag dom_id(facility, :bookmark_facility) do %>
  <%= link_to bookmarks_path(facility_id: facility.id),
              id: "js-bookmark-button-for-facility-#{facility.id}",
              data: { turbo_method: :post } do %>
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      stroke-width="1"
      stroke="currentColor"
      class="w-8 h-8"
    >
      <path
        stroke-linecap="round"
        stroke-linejoin="round"
        d="M17.593 3.322c1.1.128 1.907 1.077 1.907 2.185V21L12 17.25 4.5 21V5.507c0-1.108.806-2.057 1.907-2.185a48.507 48.507 0 0111.186 0z"　/>
    </svg>
  <% end %>
<% end %>

app/views/facilities/_bookmark_button.html.erb
<% if current_user.bookmark?(facility) %>
    <%= render 'unbookmark', {facility: facility} %>
<% else %>
    <%= render 'bookmark', {facility: facility} %>
<% end %>

app/views/facilities/_facility.html.erb
<div class="card mx-auto w-4/5 max-w-2xl sm:max-w-screen-md my-10 border border-slate-500">
  <div class="card-body sm:mx-6">
    <div class="font-semibold text-center text-xl">
      <%= link_to facility.name, facility_path(facility) %>
    </div>
    <span class="absolute top-2 right-2 w-10 h-10 p-0 border-0 inline-flex items-center justify-center text-gray-500 ml-4">
      <% if logged_in? %>
        <%= render 'bookmark_button', { facility: facility } %>
      <% else %>
        <%= render 'before_login_bookmark' %>
      <% end %>
    </span>
    <!-- ジャンル表示 -->
    <div class="mb-3 text-right">
      <% facility.genres.each do |genre| %>
        <span class="inline-flex items-center rounded-md bg-gray-50 me-1 px-2.5 py-0.5 text-xs font-medium text-gray-600 ring-1 ring-inset ring-gray-400" >
          <%= genre.name %>
        </span>
      <% end %>
    </div>
    <div class="border-t border-gray-100">
      <dl class="divide-y divide-gray-100">
        <div class="p-2 sm:grid sm:grid-cols-3 sm:gap-1 sm:px-0">
          <dt class="text-sm font-medium font-semibold leading-6"><%= t(Facility.human_attribute_name(:address)) %></td>
          <dd class="mt-1 text-sm leading-6 text-gray-700 sm:col-span-2 sm:mt-0"><%= facility.address %></td>
        </div>
        <div class="p-2 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-0">
          <dt class="text-sm font-medium font-semibold leading-6"<%= t(Facility.human_attribute_name(:opening_hour)) %></td>
          <dd class="mt-1 text-sm leading-6 text-gray-700 sm:col-span-2 sm:mt-0"><%= facility.opening_hour %></td>
        </div>
        <div class="p-2 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-0">
          <dt class="text-sm font-medium font-semibold leading-6"<%= t(Facility.human_attribute_name(:closed_on)) %></td>
          <dd class="mt-1 text-sm leading-6 text-gray-700 sm:col-span-2 sm:mt-0"><%= facility.closed_on %></td>
        </div>
      </dl>
    </div>
  </div>
</div>

app/views/facilities/_unbookmark.html.erb
<%= turbo_frame_tag dom_id(facility, :bookmark_facility) do %>
  <%= link_to bookmark_path(current_user.bookmarks.find_by(facility_id: facility.id)),
              id: "js-bookmark-button-for-facility-#{facility.id}",
              data: {turbo_method: :delete} do %>
      <svg
        xmlns="http://www.w3.org/2000/svg"
        fill="none"
        viewBox="0 0 24 24"
        stroke-width="1"
        stroke="currentColor"
        class="w-8 h-8">
        <path
          stroke-linecap="round"
          stroke-linejoin="round"
          d="M3 3l1.664 1.664M21 21l-1.5-1.5m-5.485-1.242L12 17.25 4.5 21V8.742m.164-4.078a2.15 2.15 0 011.743-1.342 48.507 48.507 0 0111.186 0c1.1.128 1.907 1.077 1.907 2.185V19.5M4.664 4.664L19.5 19.5" />
      </svg>
  <% end %>
<% end %>

app/views/facilities/bookmarks.html.erb
<!-- ブックマーク一覧 -->
<div class="container px-4 mt-10 mb-14 w-full md:container md:mx-auto">
  <div class="text-center">
    <h1 class="text-2xl font-medium font-semibold mb-4 sm:text-xl"><%= t('.title') %></h1>
  </div>
  <% if @bookmark_facilities.present? %>
    <div class='font-medium text-lg text-center mb-4'>
      <%= "#{@bookmark_facilities.count}件" %>
    </div>
    <%= render partial: 'facility', collection: @bookmark_facilities %>
  <% else %>
    <div class="mt-20 text-center">
      <p><%= t('.no_result') %></p>
    </div>
  <% end %>
</div>

app/views/facilities/index.html.erb
<div class="container mx-auto items-center px-4 mt-10 mb-14 w-full">
  <div class="text-center">
    <h1 class="text-2xl font-medium font-semibold mb-4 sm:text-xl"><%= t('.title') %></h1>
  </div>
  <!-- 施設一覧 -->
  <% if @facilities.present? %>
    <div class='font-medium text-lg text-center mb-4'>
      <%= "#{@facilities.count} 件" %>
    </div>
    <%= render @facilities %>
  <% else %>
    <div class="text-center my-20">
      <p><%= t('.no_result') %></p>
    </div>
  <% end %>
  <div class="flex mx-auto justify-center mt-4 mb-14">
    <%= link_to t('defaults.back_to_search'), root_path, class: 'btn btn-ghost btn-sm font-normal px-4' %>
  </div>
</div>

app/views/facilities/show.html.erb
<div class="container flex flex-col mx-auto items-center mt-4">
  <div class="card w-11/12 max-w-3xl mt-10 mb-10 border border-slate-500">
    <div class="py-8 px-3 max-w-3xl sm:px-12">
      <h1 class="font-semibold text-center text-2xl my-2"><%= @facility.name %></h1>
      <span class="absolute top-4 right-4 w-10 h-10 p-0 border-0 inline-flex items-center justify-center text-gray-500 ml-4">
        <% if logged_in? %>
          <%= render 'bookmark_button', { facility: @facility } %>
        <% else %>
          <%= render 'before_login_bookmark' %>
        <% end %>
      </span>
      <!-- ジャンル表示 -->
      <h2 class="my-4 pr-5 text-right">
        <% @facility.genres.each do |genre| %>
          <span class="inline-flex items-center rounded-md bg-gray-50 me-1 px-2.5 py-0.5 text-sm font-medium text-gray-600 ring-1 ring-inset ring-gray-400" >
            <%= genre.name %>
          </span>
        <% end %>
      </h2>
      <!-- 施設情報詳細 -->
      <table class="table mx-auto w-9/12 max-w-2xl">
        <tbody>
          <tr>
            <td class="text-normal font-medium font-semibold leading-tight"><%= t(Facility.human_attribute_name(:description)) %></td>
            <td class="text-sm font-light leading-5 whitespace-normal"><%= @facility.description %></td>
          </tr>
          <tr>
            <td class="text-normal font-medium font-semibold leading-tight"><%= t(Facility.human_attribute_name(:opening_hour)) %></td>
            <td class="mt-1 text-sm font-light leading-tight text-justify sm:col-span-2 sm:mt-0"><%= @facility.opening_hour %></td>
          </tr>
          <tr>
            <td class="text-normal font-medium font-semibold leading-tight"><%= t(Facility.human_attribute_name(:closed_on)) %></td>
            <td class="mt-1 text-sm font-light leading-tight sm:col-span-2 sm:mt-0"><%= @facility.closed_on %></td>
          </tr>
          <tr>
            <td class="text-normal font-medium font-semibold leading-tight"><%= t(Facility.human_attribute_name(:website)) %></td>
            <td class="mt-1 text-sm font-light leading-tight text-blue-700 sm:col-span-2 sm:mt-0">
              <%= link_to @facility.website, @facility.website, target: :_blank, rel: 'noopener noreferrer' %>
            </td>
          </tr>
          <tr>
            <td class="text-normal font-medium font-semibold leading-tight"><%= t(Facility.human_attribute_name(:address)) %></td>
            <td class="mt-1 text-sm font-light leading-tight sm:col-span-2 sm:mt-0"><%= @facility.address %></td>
          </tr>
        </tbody>
      </table>
      <div class="mx-auto p-2 border sm:px-4 max-w-3xl items-center">
        <div id="map"></div>
      </div>
    </div>
  </div>

  <!-- 口コミ表示 -->
  <h2 class="text-center text-xl font-semibold"><%= t('activerecord.models.review') %></h2>
  <% if logged_in? %>
    <!-- 口コミ一覧 -->
    <%= render 'reviews/reviews', { reviews: @reviews } %>

    <!-- 口コミ投稿 -->
    <button class="flex mx-auto mt-6" >
      <%= link_to t('reviews.post_review'),  new_facility_review_path(@facility), class: 'btn btn-wide btn-neutral text-white' %>
    </button>
  <% else %>
    <div class="flex justify-center text-center mx-auto">
      <%= link_to login_path, class: 'btn btn-neutral btn-wide h-min text-white' do %>
        <p><%= t('reviews.login_to_post_reviews') %></p>
      <% end %>
    </div>
  <% end %>

  <div class="flex mx-auto justify-center mt-4 mb-14">
    <%= link_to t('defaults.back_to_search'), root_path, class: 'btn btn-ghost btn-sm font-normal px-4' %>
  </div>
</div>

<!-- Googleマップ表示用Javascript -->
<script>
  function initMap(){
    // 地図の位置情報(緯度・経度)を取得
    let mapPosition = {lat: <%= @facility.latitude || 0 %> , lng: <%= @facility.longitude || 0 %> };
    let map = new google.maps.Map(document.getElementById('map'), {
      zoom: 15,
      center: mapPosition
    });
    let transitLayer = new google.maps.TransitLayer();
    transitLayer.setMap(map);

    let contentString = '住所<%= @facility.address %>';
    let infowindow = new google.maps.InfoWindow({
      content: contentString
    });

    let marker = new google.maps.Marker({
      position: mapPosition,
      map: map,
      title: contentString
    });

    marker.addListener('click', function(){
      infowindow.open(map, marker);
    });
  }
</script>

<script async defer
src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap">
</script>

<style>
  #map {
    height: 300px;
    width: 100%;
  }
</style>