config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :bookmarks
      resources :facilities
      resources :facility_genres
      resources :genres
      resources :prefectures
      resources :reviews
      resources :users

      root to: "facilities#index"
    end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  mount LetterOpenerWeb::Engine, at: "letter_opener" if Rails.env.development?
  # Defines the root path route ("/")
  root "static_pages#top"

  get 'guest_login', to: 'user_sessions#guest_login'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  get 'sign_up', to: 'users#new'
  get 'confirm_withdraw', to: 'users#confirm_withdraw'

  get 'privacy_policy', to: 'static_pages#privacy_policy'
  get 'terms_of_use', to: 'static_pages#terms_of_use'

  resources :bookmarks, only: %i[create destroy]
  resources :facilities, only: %i[index show]  do
    resources :reviews, shallow: true do
      resources :likes, only: %i[create destroy]
    end

    collection do
      get :bookmarks
    end
  end
  resources :users, only: %i[create destroy]
  resource :profile, only: %i[show edit update]
  resources :password_resets, only: %i[new create edit update]

end

app/controllers/admin/reviews_controller.rb
module Admin
  class ReviewsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes(action_name)).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-demo.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @facility = Facility.find(params[:facility_id])
    @review = Review.new
  end

  def create
    review = current_user.reviews.build(review_params)
    if review.save
      redirect_to facility_path(review.facility), success: t('defaults.message.posted', item: Review.model_name.human)
    else
      redirect_to facility_path(review.facility), error: t('defaults.message.not_posted', item: Review.model_name.human)
    end
  end

  def edit
    @review = current_user.reviews.find(params[:id])
  end

  def update
    @review = current_user.reviews.find(params[:id])
    if @review.update(update_review_params)
      redirect_to facility_path(@review.facility), success: t('defaults.message.updated', item: Review.model_name.human)
    else
      flash.now[:error] = t('defaults.message.not_updated', item: Review.model_name.human)
      render :edit
    end
  end

  def destroy
    review = current_user.reviews.find(params[:id])
    review.destroy!
    redirect_to facility_path(review.facility), success: t('defaults.message.deleted', item: Review.model_name.human)
  end

  private

  def review_params
    params.require(:review).permit(:body, :review_image, :review_image_cache).merge(facility_id: params[:facility_id])
  end

  def update_review_params
    params.require(:review).permit(:body, :review_image, :review_image_cache)
  end
end

app/views/reviews/_crud_menus.html.erb
<ul class='flex mt-1 pr-1'>
  <li class="list-inline-item">
    <%= link_to edit_review_path(review) do %>
      <svg class="h-7 w-7 text-gray-500"  width="24" height="24" viewBox="0 0 24 24" stroke-width="1" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">  <path stroke="none" d="M0 0h24v24H0z"/>  <path d="M4 20h4l10.5 -10.5a1.5 1.5 0 0 0 -4 -4l-10.5 10.5v4" />  <line x1="13.5" y1="6.5" x2="17.5" y2="10.5" /></svg>
    <% end %>
  </li>
  <li class="list-inline-item">
    <%= link_to review_path(review), data: {turbo_method: :delete, turbo_confirm: t('defaults.message.confirm_delete')} do %>
      <svg class="h-7 w-7 text-gray-500"  width="24" height="24" viewBox="0 0 24 24" stroke-width="1" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">  <path stroke="none" d="M0 0h24v24H0z"/>  <line x1="4" y1="7" x2="20" y2="7" />  <line x1="10" y1="11" x2="10" y2="17" />  <line x1="14" y1="11" x2="14" y2="17" />  <path d="M5 7l1 12a2 2 0 0 0 2 2h8a2 2 0 0 0 2 -2l1 -12" />  <path d="M9 7v-3a1 1 0 0 1 1 -1h4a1 1 0 0 1 1 1v3" /></svg>
    <% end %>
  </li>
</ul>

app/views/reviews/_form.html.erb
<div class="p-2 w-full">
  <div class="mx-4">
    <%= form_with model: review, url: [facility, review], local: true do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :body, class: 'my-1 block text-sm font-medium' %>
      <%= f.text_area :body,
            class: 'block w-full bg-gray-100 bg-opacity-50 rounded border border-gray-400 focus:border-gray-500 focus:bg-white focus:ring-2 focus:ring-gray-200 h-32 text-base outline-none text-gray-700 py-1 px-3 resize-none leading-6 transition-colors duration-200 ease-in-out',
            placeholder: Review.human_attribute_name(:body)%>
      <div class="my-6", data-controller="preview-image">
        <%= f.label :review_image, class: 'my-1 block text-sm font-medium' %>
        <%= f.file_field :review_image, accept: 'image/*',
              data: { action: 'change->preview-image#preview' },
              class: 'block border border-gray-400 shadow-sm rounded-lg text-sm focus:z-10 focus:border-blue-500 focus:ring-blue-500 disabled:opacity-50 disabled:pointer-events-none file:bg-gray-50 file:border-0 file:bg-gray-200 file:me-4 file:py-2 file:px-4' %>
        <%= f.hidden_field :image_cache %>
      </div>
      <div class="flex justify-center my-3">
        <%= image_tag review.review_image.url, id: 'preview', size: '200x200' %>
      </div>
      <div class="actions mt-10 text-center normal-case">
        <%= f.submit t('defaults.post'), class: 'btn btn-wide btn-neutral text-white' %>
      </div>
    <% end %>
  </div>
</div>

app/views/reviews/_like.html.erb
<%= turbo_frame_tag dom_id(review, :like_review) do %>
  <%= link_to review_likes_path(review_id: review.id),
              id: "js-like-button-for-review-#{review.id}",
              data: { turbo_method: :post } do %>
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="32" height="32" viewBox="0 0 24 24">
      <path
        fill="none"
        stroke="currentColor"
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-width="1"
        d="M4.318 6.318a4.5 4.5 0 0 0 0 6.364L12 20.364l7.682-7.682a4.5 4.5 0 0 0-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 0 0-6.364 0Z"/>
    </svg>
  <% end %>
<% end %>

app/views/reviews/_like_button.html.erb
<% if current_user.like?(review) %>
    <%= render 'reviews/unlike', {review: review} %>
<% else %>
    <%= render 'reviews/like', {review: review} %>
<% end %>

app/views/reviews/_review.html.erb
<div class="card w-3/4 md:max-w-2xl p-4 mx-4 my-6 border border-slate-500">
  <div class="px-2">
    <div class="flex flex-row">
      <div class="mx-2">
        <%= image_tag review.user.avatar_url, class: 'avatar rounded-xl w-12 h-12'%>
      </div>
      <div class="ml-3 mt-4">
        <span class="text-sm font-semibold tracking-widest text-blue-500"><%= review.user.name %></span>
        <span class="text-xs text-light text-gray-500 ml-1"><%= review.updated_at.strftime('%Y/%m/%d %H:%M')%></span>
      </div>
    </div>
    <div class="absolute top-2 right-2">
      <% if current_user.own?(review) %>
        <%= render 'reviews/crud_menus', review: review %>
      <% else %>
        <%= render 'reviews/like_button', review: review %>
      <% end %>
    </div>
    <div class="flex mx-auto mt-2">
      <p class="text-base text-sm leading-normal tracking-normal break-all">
        <%= review.body %>
      </p>
    </div>
    <div class="flex justify-center mx-auto m-2 items-center">
      <%= image_tag review.review_image_url, class: 'card-img-top', size: '150x150'if review.review_image.present? %>
    </div>
  </div>
</div>

app/views/reviews/_reviews.html.erb
<% if @reviews.present? %>
  <%= render @reviews %>
<% else %>
  <p class="text-center my-6"><%= t('reviews.no_result') %></p>
<% end %>

app/views/reviews/_unlike.html.erb
<%= turbo_frame_tag dom_id(review, :like_review) do %>
  <%= link_to like_path(current_user.likes.find_by(review_id: review.id)),
              id: "js-like-button-for-review-#{review.id}",
              data: {turbo_method: :delete} do %>
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="32" height="32" viewBox="0 0 20 20">
        <path
          fill="currentColor"
          fill-rule="evenodd"
          d="M3.172 5.172a4 4 0 0 1 5.656 0L10 6.343l1.172-1.171a4 4 0 1 1 5.656 5.656L10 17.657l-6.828-6.829a4 4 0 0 1 0-5.656Z" clip-rule="evenodd"/>
      </svg>
  <% end %>
<% end %>

app/views/reviews/edit.html.erb
<div class="mt-10 mb-14 w-full">
  <div class="mx-auto max-w-2xl">
    <div class="flex flex-col text-center w-full mb-8">
      <h1 class="text-2xl font-medium font-semibold mb-4 sm:text-xl"><%= t('.title') %></h1>
    </div>
    <!-- 口コミ投稿フォーム -->
    <%= render 'form', { facility: @facility, review: @review } %>
  </div>
  <%= render 'shared/back_to_previous_page' %>
</div>

app/views/reviews/new.html.erb
<div class="mx-auto mt-10 mb-14 w-full">
  <div class="mx-auto max-w-2xl">
    <div class="flex flex-col text-center w-full mb-8">
      <h1 class="text-2xl font-medium font-semibold mb-4 sm:text-xl"><%= t('.title') %></h1>
    </div>
    <!-- 口コミ投稿フォーム -->
    <%= render 'form', { facility: @facility, review: @review } %>
  </div>
  <%= render 'shared/back_to_previous_page' %>
</div>