config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :bookmarks
      resources :facilities
      resources :facility_genres
      resources :genres
      resources :prefectures
      resources :reviews
      resources :users

      root to: "facilities#index"
    end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  mount LetterOpenerWeb::Engine, at: "letter_opener" if Rails.env.development?
  # Defines the root path route ("/")
  root "static_pages#top"

  get 'guest_login', to: 'user_sessions#guest_login'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  get 'sign_up', to: 'users#new'
  get 'confirm_withdraw', to: 'users#confirm_withdraw'

  get 'privacy_policy', to: 'static_pages#privacy_policy'
  get 'terms_of_use', to: 'static_pages#terms_of_use'

  resources :bookmarks, only: %i[create destroy]
  resources :facilities, only: %i[index show]  do
    resources :reviews, shallow: true do
      resources :likes, only: %i[create destroy]
    end

    collection do
      get :bookmarks
    end
  end
  resources :users, only: %i[create destroy]
  resource :profile, only: %i[show edit update]
  resources :password_resets, only: %i[new create edit update]

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create guest_login]

  def new; end

  def create
    @user = login(params[:email], params[:password])
    if @user
      redirect_back_or_to root_path, success: t('.success')
    else
      flash.now[:error] = t('.fail')
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    logout
    redirect_to root_path, success: t('.success')
  end

  def guest_login
    user = User.guest
    auto_login(user)
    redirect_to root_path, success: t('.success')
  end
end

app/views/user_sessions/_form.html.erb
<div class="flex flex-col mt-10">
  <%= form_with(model: user, url: login_path, local: true) do |f| %>
    <div class="my-5">
      <%= f.label :email, User.human_attribute_name(:email), class: 'my-1 block text-sm font-medium' %>
      <%= f.text_field :email, id: 'email', class: 'block w-full rounded-md border-gray-300 shadow-sm focus:border-gray-400 focus:ring focus:ring-gray-200 focus:ring-opacity-50', autocomplete: 'email' %>
    </div>
    <div class="my-5">
      <%= f.label :password, User.human_attribute_name(:password), class: 'my-1 block text-sm font-medium'  %>
      <%= f.password_field :password, id: 'password', class: 'block w-full rounded-md border-gray-300 shadow-sm focus:border-gray-400 focus:ring focus:ring-gray-200 focus:ring-opacity-50', autocomplete: 'off' %>
      <%= link_to t('user_sessions.new.password_forget'), new_password_reset_path, class: 'mt-2 label-text-alt link text-gray-500' %>
    </div>
    <div class="actions mt-8 text-center normal-case">
      <%= f.submit t('defaults.login'), class: 'btn btn-wide btn-neutral text-white' %>
    </div>
  <% end %>
</div>

app/views/user_sessions/new.html.erb
<div class="mt-10 mb-14 w-full">
  <div class="mx-auto max-w-sm">
    <div class="flex flex-col text-center w-full mb-8">
      <h1 class="text-2xl font-medium font-semibold mb-4 sm:text-xl"><%= t('.title') %></h1>
    </div>
    <%= render 'form', user: @user %>
    <div class='my-5 text-center text-sm text-gray-500 label-text-alt link link-hover'>
      <%= link_to t('.to_register_page'), sign_up_path %>
    </div>
    <div class="flex flex-col mx-auto my-20 text-center normal-case">
      <p class="mb-3">登録せずに試してみる</p>
      <div class="flex mx-auto">
        <%= link_to t('.login_as_guest'), guest_login_path, class: 'btn btn-outline btn-wide' %>
      </div>
    </div>
  </div>
</div>